export const WEAPONS_DATA = {
    GUN: {
        type: 'GUN',
        shopAsset: 'assets/items/Dague.png',
        asset: 'assets/items/Revolver.png',
        bulletAsset: 'assets/items/StandartBullet.png',
        bulletSize: { w: 12, h: 6 },
        radius: 32, width: 32, height: 16,
        powerMult: 1.0, gravityMult: 1.0,
        maxDamage: 30
    },
    MACHINEGUN: {
        type: 'MACHINEGUN',
        shopAsset: 'assets/items/Sword.png',
        asset: 'assets/items/MachineGun.png',
        bulletAsset: 'assets/items/StandartBullet.png',
        bulletSize: { w: 12, h: 6 },
        radius: 24, width: 40, height: 18,
        powerMult: 0.5, gravityMult: 1.0,
        maxDamage: 12,
        burstCount: 3, burstDelay: 120
    },
    SHOTGUN: {
        type: 'SHOTGUN',
        shopAsset: 'assets/items/Kunai.png',
        asset: 'assets/items/Shotgun.png',
        bulletAsset: 'assets/items/StandartBullet.png',
        bulletSize: { w: 14, h: 6 },
        radius: 40, width: 40, height: 20,
        powerMult: 0.55, gravityMult: 0.9,
        maxDamage: 8,
        spreadCount: 5, spreadAngle: 0.18
    },
    BAZOOKA: {
        type: 'BAZOOKA',
        shopAsset: 'assets/items/FireBall.png',
        asset: 'assets/items/Bazooka.png',
        bulletAsset: 'assets/items/BombBox.png',
        bulletSize: { w: 22, h: 22 },
        radius: 128, width: 48, height: 32,
        powerMult: 0.8, gravityMult: 1.4,
        minDamage: 10,
        maxDamage: 50
    },
    SNIPER: {
        type: 'SNIPER',
        shopAsset: 'assets/items/Bow.png',
        asset: 'assets/items/Sniper.png',
        bulletAsset: 'assets/items/StandartBullet.png',
        bulletSize: { w: 15, h: 4 },
        radius: 32, width: 48, height: 32,
        powerMult: 2.5, gravityMult: 0.1,
        maxDamage: 70
    },
    GRENADE: {
        type: 'GRENADE',
        shopAsset: 'assets/items/Grenade.png',
        asset: 'assets/items/Grenade.png',
        bulletAsset: 'assets/items/Grenade.png',
        bulletSize: { w: 20, h: 20 },
        radius: 128,
        width: 20, height: 20,
        powerMult: 0.8, gravityMult: 1.0,
        isGrenade: true,
        minDamage: 15,
        maxDamage: 45,
        fuseTime: 3000,
    },
    FRAGMENTATION: {
        type: 'FRAGMENTATION',
        shopAsset: 'assets/items/Grenade.png',
        asset: 'assets/items/Grenade.png',
        bulletAsset: 'assets/items/Grenade.png',
        bulletSize: { w: 20, h: 20 },
        radius: 128,
        width: 20, height: 20,
        powerMult: 0.8, gravityMult: 1.0,
        isGrenade: true,
        isFragmentation: true,
        minDamage: 7,
        maxDamage: 23,
        fuseTime: 3000,
        fragmentCount: 6,
    },
    FRIDGE: {
        type: 'FRIDGE',
        shopAsset: 'assets/items/FlonFlon.png',
        asset: 'assets/items/Frigogidaire.png',
        bulletAsset: 'assets/items/Frigogidaire.png',
        bulletSize: { w: 48, h: 48 },
        radius: 256,
        width: 48, height: 48,
        powerMult: 1.0, gravityMult: 3.0,
        minDamage: 20,
        maxDamage: 70,
        isFridge: true
    },
    HEAL: {
        type: 'HEAL',
        shopAsset: 'assets/items/HealPotion.png',
        asset: 'assets/items/HealPotion.png',
        bulletAsset: 'assets/items/HealPotion.png',
        bulletSize: { w: 24, h: 24 },
        radius: 0, width: 24, height: 24,
        powerMult: 1.0, gravityMult: 1.0,
        isHeal: true,
        healFlat: 30,
        healPercent: 0.30,
        maxAmmo: 3,
    },
    JUMPPOTION: {
        type: 'JUMPPOTION',
        shopAsset: 'assets/items/JumpPotion.png',
        asset: 'assets/items/JumpPotion.png',
        bulletAsset: 'assets/items/JumpPotion.png',
        bulletSize: { w: 24, h: 24 },
        radius: 0, width: 24, height: 24,
        powerMult: 1.0, gravityMult: 1.0,
        isJumpPotion: true,
        extraJumps: 3,
        maxAmmo: 2,
    },
};

export const CLASS_WEAPONS = {
    warrior: ['GUN', 'MACHINEGUN'],
    wizard:  ['GUN', 'BAZOOKA'],
    archer:  ['GUN', 'SNIPER'],
};

export const WEAPON_NAMES = {
    GUN:         'Revolver',
    MACHINEGUN:  'AK-47 (Rafale)',
    SHOTGUN:     'Fusil à Pompe',
    BAZOOKA:     'Bazooka',
    SNIPER:      'Sniper',
    GRENADE:     'Grenade',
    FRAGMENTATION: 'Grenade à Fragmentation',
    FRIDGE:      'Frigogidaire',
    HEAL:        'Potion de Soins',
    JUMPPOTION:  'Potion de Saut',
};

export const WEAPON_COST = {
    GUN:        0,
    MACHINEGUN: 75,
    SHOTGUN:    75,
    BAZOOKA:    75,
    SNIPER:     75,
    GRENADE:    50,
    FRAGMENTATION: 100,
    FRIDGE:     250,
    HEAL:       50,
    JUMPPOTION: 50,
};
